# Generated by Django 4.2.25 on 2025-11-02 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nameofproblem', models.CharField(max_length=20)),
                ('descriptionofproblem', models.CharField(max_length=200)),
                ('categoryofproblem', models.CharField(choices=[('windows', 'Windows'), ('account', 'Account'), ('connection', 'Connection lost'), ('updates', 'Updates'), ('virus', 'Virus'), ('other', 'Others')], max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('old', 'old'), ('in_progress', 'In Progress'), ('closed_session', 'Closed Session'), ('blocked/reported', 'Blocked')], max_length=20)),
                ('usedproblem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Meetings', to='bookingapp.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
