# Generated by Django 4.2.25 on 2025-11-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='Nameofproblem',
            new_name='nameofproblem',
        ),
    ]
