# Generated by Django 4.2.25 on 2025-11-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_rename_nameofproblem_problem_nameofproblem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('old', 'old'), ('in_progress', 'In Progress'), ('closed_session', 'Closed Session'), ('blocked/reported', 'Blocked')], default='new', max_length=20),
        ),
    ]
