# Generated by Django 4.2.25 on 2025-11-23 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_alter_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='datetimemeet',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 23, 19, 15, 52, 686681, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
